server:
  name: "FREE KEY"
  address: ":1211"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  serverRoot: "resource/public"
  dumpRouterMap: true
  routeOverWrite: true
  jwtExpireDuration: "7D" # 7 days
  imgPrefix: "http://localhost:1211/upload/" # 图片前缀
  rootFilePath: "/resource/public/upload/"  # 文件上传路径
  rootIp: "localhost"
  rootPath: "/home/holw/learn/ciel-admin/"
  clientMaxBodySize: "200MB"

home: "/menu/path"

logger:
  path: "logs/default"
  level: "all"
  stdout: true

# 模板引擎配置
viewer:
  paths:
    - "resource/template"
# Database.
database:
  logger:
    level: "all"
    stdout: true
  default:
    link: "mysql:ciel:2zL4YEdLpLJirysN@tcp(127.0.0.1:3306)/ciel"
    debug: true

redis:
  default:
    address: "127.0.0.1:6379"
    db: 1
    pass: ""

# CLI.
gfcli:
  gen:
    dao:
      - link: "mysql:ciel:2zL4YEdLpLJirysN@tcp(127.0.0.1:3306)/ciel"
        tables: "s_admin,s_role,s_menu,s_role_menu,s_api,s_role_api,s_dict,s_file,s_operation_log,
         f_node"
        removePrefix: "s_,f_"
        descriptionTag: true
        noModelComment: true
html:
  status:
    - value: 1
      label: 正常
      class: tag-info
    - value: 2
      label: 禁用
      class: tag-danger
  method:
    - value: 1
      label: GET
      class: tag-success
    - value: 2
      label: POST
      class: tag-primary
    - value: 3
      label: PUT
      class: tag-warning
    - value: 4
      label: DELETE
      class: tag-danger