server:
  address: ":1211"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  serverRoot: "resource/public"
  dumpRouterMap: true
  routeOverWrite: true
  jwtExpireDuration: "7D" # 7 days
  imgPrefix: "http://localhost:1211/upload/" # 图片前缀
  rootFilePath: "/resource/public/upload/"  # 文件上传路径
  modName: "ciel-admin"  # 生成文件时使用
  rootIp: "localhost"

logger:
  path: "logs/default"
  level: "all"
  stdout: true

# 模板引擎配置
viewer:
  paths:
    - "resource/template"

# Database.
database:
  logger:
    level: "all"
    stdout: true
  default:
    link: "mysql:ciel:2zL4YEdLpLJirysN@tcp(127.0.0.1:3306)/ciel"
    debug: true

redis:
  default:
    address: "127.0.0.1:6379"
    db: 1
    pass: "12*33KdwefaDIjAEfo"

# CLI.
gfcli:
  gen:
    dao:
      - link: "mysql:ciel:2zL4YEdLpLJirysN@tcp(127.0.0.1:3306)/ciel"
        tables: "s_admin,s_role,s_menu,s_role_menu,s_api,s_role_api,s_file,
        u_user,u_login_log
        "
        removePrefix: "s_,u_"
        descriptionTag: true
        noModelComment: true
rss:
  - "V2EX:/"
  - "Github:/sys/path/github"
  - "豆瓣阅读:/sys/path/douban"
  - "开源中国:/sys/path/oschina"