server:
  address: ":1211"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  serverRoot: "resource/public"
  dumpRouterMap: true
  routeOverWrite: true
  jwtExpireDuration: "7D" # 7 days
  imgPrefix: "http://localhost:1211/upload/" # 图片前缀
  rootFilePath: "/resource/public/upload/"  # 文件上传路径
  modName: "ciel-admin"  # 生成文件时使用
  rootIp: "localhost"

logger:
  path: "logs/default"
  level: "all"
  stdout: true

# 模板引擎配置
viewer:
  paths:
    - "resource/template"

# Database.
database:
  logger:
    level: "all"
    stdout: true
  default:
    link: "mysql:ciel:2zL4YEdLpLJirysN@tcp(127.0.0.1:3306)/ciel"
    debug: true

redis:
  default:
    address: "127.0.0.1:6379"
    db: 1
    pass: ""

# CLI.
gfcli:
  gen:
    dao:
      - link: "mysql:ciel:2zL4YEdLpLJirysN@tcp(127.0.0.1:3306)/ciel"
        tables: "s_admin,s_role,s_menu,s_role_menu,s_api,s_role_api,s_file,
        u_user,u_login_log
        "
        removePrefix: "s_,u_"
        descriptionTag: true
        noModelComment: true
rss:
  - "V2EX:/"
  - "Github:/sys/path/github"
  - "豆瓣阅读:/sys/path/douban"
  - "开源中国:/sys/path/oschina"
table:
  menu:
    name: Menu
    desc: 这里是Menu管理页面,可以对菜单进行添加,修改,删除等操作。
    urlPrefix: /menu/
    icon: /upload/1/2022/03/FdI4Yw.gif
    fields:
      - field: id
        label: ID
      - field: pid
        label: pid
        search: 1
      - field: name
        label: 菜单名
        search: 1
      - field: icon
        label: 图标
        type: img
      - field: path
        label: 路径
      - field: type
        label: 类型
        type: select
        options:
          - value: 1
            label: 菜单
            type: primary
          - value: 2
            label: 分组
            type: warning
      - field: sort
        label: 排序
        type: number
      - field: status
        label: 状态
        type: select
        options:
          - value: 1
            label: 正常
            type: info
          - value: 2
            label: 禁用
            type: danger
      - field: created_at
        label: 创建时间
      - field: updated_at
        label: 更新时间
        notShow: 1
      - field: 操作
        type: operate