server:
  address: ":2022"
  serverRoot: "resource/public"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  jwtExpireDuration: "7D"
  rootFilePath: "/home/howl/learn/ciel-admin/interface/resource/public/resource/upload"

logger:
  level: "all"
  stdout: true

# Database.
database:
  logger:
    level: "all"
    stdout: true
  default:
    link: "mysql:ciel_admin:123456@tcp(127.0.0.1:3306)/ciel_admin"
    debug: true

redis:
  default:
    address: "127.0.0.1:6379"
    db: 1

# CLI.
gfcli:
  gen:
    dao:
      - link: "mysql:ciel_admin:123456@tcp(127.0.0.1:3306)/ciel_admin"
        tables: "s_admin,s_api,s_menu,s_role,s_role_api,s_role_menu,s_dict,s_file"
        removePrefix: "s_"
        descriptionTag: true
        noModelComment: true
